spring:
  application:
    name: sosa-client
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sosa
      client:
        registration:
          keycloak:
            client-id: sosa-client
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/sosa
            user-name-attribute: preferred_username

keycloak:
  realm: sosa
  resource: sosa-client
  auth-server-url: http://localhost:8080

server:
  port: 8082
