spring:
  application:
    name: sosa-client
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sosa
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  realm: "sosa"
  resource: "sosa-client"
  auth-server-url: "http://localhost:8080"

jwt:
  auth:
    converter:
      resource-id: sosa-client
      principal-attribute: preferred_username

server:
  port: "8082"
